### ISSUE TITLE
Explicar melhor o termo twitter na tela de Atuação parlamentar

### ISSUE THREAD

**Issue by gileadekelvin** [parlametria/leggo-painel#116]
### Descrição
- Na tela de atuação parlamentar (lista com cards) não está claro o que significa o termo "twitter" na barra azul.

![image](https://user-images.githubusercontent.com/10724115/94049089-df3ff600-fdaa-11ea-9d29-f69f992a8254.png)

**Comment by nazareno** [comment]
temos esse design no mockup mais atual 

![Uploading image.png…]()
