### ISSUE TITLE
Uma casa decimal sempre que possível

### ISSUE THREAD

**Issue by nazareno** [parlametria/leggo-painel#134]
Não precisamos de muita precisão, e facilitará a legibilidade se usarmos apenas uma casa decimal nas autorias, e em todo lugar onde os valores não forem sempre menores que 0,05. Para reduzir o número de casas, lembrar de arredondar: 0.08 vira 0.1. 

![image](https://user-images.githubusercontent.com/1053850/96605429-935e6f00-12cc-11eb-9357-e08677edaaaf.png)

**Comment by gileadekelvin** [comment]
Não faz mais sentido. Valores absolutos foram adotados
