### ISSUE TITLE
Regra de destaque para PECs

### ISSUE THREAD

**Issue by nazareno** [parlametria/leggo-painel#245]
A PEC não tem urgência, então ela deve entrar em destaque de "avançou nas comissões" quando for aprovada **na comissão especial que é instituída no início de sua tramitação**. Ela também pode ficar em destaque por ter sido aprovada em uma casa.

**Comment by gileadekelvin** [comment]
US Criada https://tree.taiga.io/project/hadrizia-leggo/us/2384?no-milestone=1
