### ISSUE TITLE
Página de Detalhes do parlamentar - cabeçalho

### ISSUE THREAD

**Issue by ArthurJahn** [parlametria/leggo-painel#437]
![Screenshot from 2022-02-14 15-48-03](https://user-images.githubusercontent.com/2107018/153927078-c84fbd3d-42c5-4e57-aff0-7f86ddd57b0f.png)

**Comment by ArthurJahn** [comment]
O link dos assets e cores -> https://xd.adobe.com/view/528f2c3d-8cde-4be5-b906-da9022c7d0dc-07dc/screen/ca553d9f-b6b2-44dc-9520-5da186c01492/ 
O link da página do parlamentar -> https://xd.adobe.com/view/6180941d-6f9a-405e-841d-3c840322850a-34d3/screen/4e36a12e-970b-4a51-a16d-496ab02c9cf6

**Comment by andersonms1** [comment]
@ArthurJahn tô com umas duvidas em relação as cores do gráfico.

![image](https://user-images.githubusercontent.com/17951542/155635979-aaddc6b2-0e27-4bd4-9f9d-030b2a7ad8b5.png)

* Essa cor é proporcional a porcentagem? Relacionado ao partido? Estado? Ou apenas fixa mesmo?

**Comment by andersonms1** [comment]
Alguma sugestão de como posso estar implementado o gráfico tambem?

**Comment by ArthurJahn** [comment]
As cores são fixas mesmo, tem duas classes já com essas cores: bg-disciplina e bg-governismo

**Comment by ArthurJahn** [comment]
A lib q a gente tá usando é a d3, acho que a alternativa é usar o donut chart

**Comment by andersonms1** [comment]
@pollyannacarvalho quando possível. Passa as dimensões da foto/mapa/gráfico do parlamentar. E botão saiba mais, por favor

**Comment by ArthurJahn** [comment]
@andersonms1 dá pra usar como base o https://xd.adobe.com/view/6180941d-6f9a-405e-841d-3c840322850a-34d3/screen/4e36a12e-970b-4a51-a16d-496ab02c9cf6/

**Comment by andersonms1** [comment]
![image](https://user-images.githubusercontent.com/17951542/158286124-09a58840-ea40-4dcb-871a-ea9de6840735.png)

 [Acredito  que para colocar essa borda redonda tenha que ter essa separação da imagem](https://stackoverflow.com/questions/50144861/add-border-radius-property-to-d3js-donut-chart). 
 
 Sendo esse o caso, qual a preferencia? Colocar a borda e ficar com espaçamento ou ficar sem borda e espaçamento.

**Comment by ArthurJahn** [comment]
Pode deixar sem, nenhum outro gráfico da plataforma usa borda arredondada.

**Comment by andersonms1** [comment]
@ArthurJahn notei que dos estados está faltando DF. Posso pegar uma `svg` do google mesmo?

![image](https://user-images.githubusercontent.com/17951542/159087072-4eb9b1cb-cd25-4d8b-8fad-9189cb767c5d.png)

**Comment by ArthurJahn** [comment]
Puts! @pollyannacarvalho vc consegue providenciar uma imagem semelhante a essas do DF pra gente? @andersonms1 enquanto isso, pode deixar qualquer placeholder da internet mesmo.

**Comment by pollyannacarvalho** [comment]
@andersonms1 @ArthurJahn segue o svg (também atualizei no design system aqui: https://xd.adobe.com/view/07e4da27-f6fb-492d-a103-8fe79a32b0cd-52b7/ ):

![DF](https://user-images.githubusercontent.com/97557344/159249549-c485503c-0b21-4921-bac6-a66fbe47276f.svg)

**Comment by andersonms1** [comment]
@pollyannacarvalho  

Por algum motivo a borda não está aparecendo como nos outros. Será a largura dela?

![image](https://user-images.githubusercontent.com/17951542/159351497-081ab3cf-8439-4aac-a86d-2eee94492211.png)
![image](https://user-images.githubusercontent.com/17951542/159352471-2b19e602-dd3d-4589-a65c-fda6e6469a49.png)

**Comment by pollyannacarvalho** [comment]
> @pollyannacarvalho
> 
> Por algum motivo a borda não está aparecendo como nos outros. Será a largura dela?
> 
> ![image](https://user-images.githubusercontent.com/17951542/159351497-081ab3cf-8439-4aac-a86d-2eee94492211.png) ![image](https://user-images.githubusercontent.com/17951542/159352471-2b19e602-dd3d-4589-a65c-fda6e6469a49.png)

@andersonms1 vish, pode ser do svg que eu exportei, ou vc pegou lá do Xd?

**Comment by pollyannacarvalho** [comment]
![DF](https://user-images.githubusercontent.com/97557344/159471670-96835d2d-55ac-4012-aa72-90e2177d20fd.svg)
@andersonms1 veja se esse vai

**Comment by andersonms1** [comment]
@pollyannacarvalho Agora foi. Obrigado!

![image](https://user-images.githubusercontent.com/17951542/159583568-86f107a6-79c0-44c3-8fb0-16132dc6ec70.png)
