### ISSUE TITLE
Consolidar tipografia com o design system - Fontes, títulos e links

### ISSUE THREAD

**Issue by ArthurJahn** [parlametria/leggo-painel#447]
Os elementos definidos no design system estão diferentes dos utilizados nas páginas do XD. É necessário padronizar os elementos e nessa issue vamos focar nas fontes, títulos e links.

**Comment by ArthurJahn** [comment]
@pollyannacarvalho vamos focar em duas páginas no momento:
 - Página de detalhe do parlamentar
 - Página de detalhe da proposição

**Comment by ArthurJahn** [comment]
@pollyannacarvalho sobe os pngs ou os links do XD aqui pra gente já fechar essa tarefa, valeu!

**Comment by pollyannacarvalho** [comment]
link atualizado do Xd https://xd.adobe.com/view/3a89afaf-552c-410c-9eae-3d2f407fcaf3-6fda/
Seguem os pngs das telas originais do projeto com as indicações pros ajustes de tipografia, no link do Xd elas já estão ajustadas. As seguintes áreas da página do parlamentar foram alteradas nessa proposta:
- Cabeçalho do parlamentar (que afeta todas as paáginas);
- A área de Votações;
- A área de Despesas.

@ArthurJahn o que acha? 

![cabecalho-ajustes](https://user-images.githubusercontent.com/97557344/164988567-9b836784-6a8c-4ead-b806-3742f13c6665.png)

![Votações – 3-ajustes](https://user-images.githubusercontent.com/97557344/164988565-ad810b6e-a32e-4e84-a34a-63ed786e61e4.png)

![Patrimônio-Despesas-ajustes](https://user-images.githubusercontent.com/97557344/164988610-55f6b870-ebdd-4ea3-bcc7-1a3d667933a4.png)

**Comment by ArthurJahn** [comment]
Ótimo, @pollyannacarvalho !
