### ISSUE TITLE
Correção dos mapas na pág. de detalhes do parlamentar

### ISSUE THREAD

**Issue by ArthurJahn** [parlametria/leggo-painel#469]

**Comment by ArthurJahn** [comment]
@andersonms1 quais alterações você relatou que precisava fazer mesmo? Que já resolvo aqui

**Comment by andersonms1** [comment]
@ArthurJahn ficaram nessa conversa do parlametria
https://pencillabsworkspace.slack.com/archives/C025GSJEPGW/p1648731554088959
