### ISSUE TITLE
Página de projetos - nova home page

### ISSUE THREAD

**Issue by ArthurJahn** [parlametria/leggo-painel#470]
Implementar a página de projetos de acordo com a proposta visual do XD

**Comment by ArthurJahn** [comment]
@fabio1079 a página tá ótima. Só gostaria que você alterasse o último quadro para o projeto "Perfil Parlamentar" e retirasse o Parlametria, já que essa página vai ficar dentro da própria plataforma.
![Screenshot from 2022-04-27 14-48-27](https://user-images.githubusercontent.com/2107018/165588420-1ebcedde-7de8-494a-87ce-a79d1d4e0309.png)

**Comment by ArthurJahn** [comment]
Pode subir como hotfix na development, pq já mergi sua branch

**Comment by fabio1079** [comment]
Subi um hotfix com a alteração: https://github.com/parlametria/leggo-painel/commit/b41289f471b6f87d106178da7bee9f5c9a42ae2a
